### ISSUE TITLE
Support libublk::sys::UBLK_F_UNPRIVILEGED_DEV

### ISSUE THREAD

**Issue by dholth** [ming1/rublk#1]
Can unprivileged work with rublk or libublk-rs? Am trying to add UBLK_F_UNPRIVILEGED_DEV to https://github.com/ming1/rublk/blob/main/src/args.rs#L44 or in libublk-rs examples, but get an error thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OtherError(-22)', examples/loop.rs:159:65

In Linux fedora 6.5.5-100.fc37.x86_64; have installed udev rules and ublk_chown.sh.

**Comment by ming1** [comment]
Yeah, UBLK_F_UNPRIVILEGED_DEV isn't supported, and it needs to be supported in libublk-rs first.

I guess the failure is from UblkDev:new(), and it may be caused
by ublk char device not setup yet by udev, you can try to add wait until /dev/ublkcN is ready in Ublkdev:new().

Thanks,

**Comment by ming1** [comment]
Now this feature is supported in v0.1.2
